<a href="https://colab.research.google.com/github/jiwoong2/deeplearning/blob/main/mininet_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch import nn

In [2]:
x = torch.randn(100,3)
layer = torch.nn.Linear(3,5)
print(layer(x).shape)
print(layer.weight)
print(layer.bias)

torch.Size([100, 5])
Parameter containing:
tensor([[ 0.3678,  0.5722, -0.2147],
        [ 0.2794, -0.4973, -0.1392],
        [ 0.4440,  0.3696, -0.3795],
        [-0.5396,  0.1880, -0.1981],
        [-0.5292,  0.1998,  0.5715]], requires_grad=True)
Parameter containing:
tensor([-0.2123,  0.1199,  0.2059,  0.3089, -0.3607], requires_grad=True)


In [3]:
x = torch.randn(2,5)
layer = torch.nn.ReLU()
print(layer(x))

tensor([[0.0000, 0.0000, 0.0030, 0.3444, 0.0000],
        [2.3252, 0.7045, 0.0000, 0.0000, 0.0000]])


In [4]:
x = torch.randn(3,7)
drop = nn.Dropout(p=0.3) # p는 죽일확률
print(x)
print(drop(x))

tensor([[-0.1539, -0.0455,  0.8011, -0.2736, -0.5154, -0.2928,  0.8686],
        [ 0.8514, -0.1296,  1.7560,  2.5745,  0.7562, -0.6695, -0.1019],
        [ 0.6727,  0.5611,  0.7939, -2.3833, -0.3115,  1.5153,  0.6839]])
tensor([[-0.0000, -0.0650,  1.1445, -0.0000, -0.0000, -0.0000,  0.0000],
        [ 1.2162, -0.0000,  2.5086,  3.6778,  1.0803, -0.9564, -0.0000],
        [ 0.9610,  0.0000,  1.1341, -0.0000, -0.0000,  2.1648,  0.9770]])


In [5]:
class sample_model(nn.Module):
    def __init__(self):
        super().__init__()
        self.drop_layer = nn.Sequential(nn.Linear(5,7),
                                        nn.Dropout(p=0.3))

    def forward(self, x):
        x = self.drop_layer(x)

        return x

model = sample_model()
model.train()
x = torch.randn(3,5)
y = torch.randn(2,3,5)
print(model(x))

model.eval() # 모두살리는 동시에 각 요소에 p를 곱해준다.
print(model(x))

tensor([[-0.2807, -0.0000, -0.1165, -0.0042,  0.0000, -0.0000,  0.0000],
        [ 0.0000, -1.8225,  1.8012, -1.2450,  1.3255, -0.2090,  1.6106],
        [ 0.0000, -2.0500,  0.0000,  0.4317,  1.1879, -0.0000,  1.4149]],
       grad_fn=<MulBackward0>)
tensor([[-0.1965, -0.3587, -0.0816, -0.0029,  0.7690, -0.6795,  0.2801],
        [ 0.3446, -1.2758,  1.2608, -0.8715,  0.9279, -0.1463,  1.1274],
        [ 0.3512, -1.4350,  0.9079,  0.3022,  0.8316, -0.2244,  0.9904]],
       grad_fn=<AddmmBackward0>)


In [6]:
layer = nn.Conv2d(in_channels=1, out_channels=2, kernel_size=3, strid=1, padding=1) # stride=1, padding=0이 default
layer(torch.randn(32,1,5,5)).shape

torch.Size([32, 2, 3, 3])

In [10]:
#shape 햇갈리니까 잘 생각.
layer = nn.Conv2d(3,5,3, padding=1, stride=2)
print(layer(torch.rand(32,3,5,5)).shape)
layer.weight.shape

torch.Size([32, 5, 3, 3])


torch.Size([5, 3, 3, 3])

In [13]:
conv1 = nn.Conv2d(1,8,6, stride=2)
x=torch.randn(32,1,28,28)
print(conv1(x).shape)

conv2 = nn.Conv2d(8,16,3, padding=1)
print(conv2(conv1(x)).shape)

Maxpool = nn.MaxPool2d(kernel_size=2, stride=(2,2))
print(Maxpool(conv2(conv1(x))).shape)

torch.Size([32, 8, 12, 12])
torch.Size([32, 16, 12, 12])
torch.Size([32, 16, 6, 6])


In [17]:
maxpool = nn.MaxPool2d(2) # 2로만줘도 kernel_size=2, strid=(2,2)
x=torch.randn(1,1,6,6)
print(x)
print(maxpool(x))

tensor([[[[-0.2443,  1.2284, -2.3478,  0.8707,  0.4839, -0.4141],
          [ 0.3479,  0.7178, -0.8183,  0.4136,  1.1103,  0.7696],
          [ 0.5983, -0.7601, -0.4293,  0.7322, -0.0848,  0.4155],
          [-0.4926,  0.4655, -1.8375, -1.4843,  3.0647, -0.8200],
          [-0.1299,  0.4026, -0.5110, -0.0790,  2.0965, -0.4386],
          [-1.3896,  0.4669,  0.8643,  1.3096, -0.7392, -1.3777]]]])
tensor([[[[1.2284, 0.8707, 1.1103],
          [0.5983, 0.7322, 3.0647],
          [0.4669, 1.3096, 2.0965]]]])


In [18]:
avgpool = nn.AvgPool2d(2)
x = torch.randn(1,1,6,6)
print(x)
print(avgpool(x))
print(avgpool(torch.randn(32,3,6,6)).shape)

tensor([[[[ 1.1395,  1.5123,  0.4370,  0.0638, -0.1156, -0.2695],
          [-1.4530, -1.1092,  0.7602, -0.2652, -0.0485,  0.2819],
          [ 0.0643,  0.4649,  1.9696, -0.7863, -1.1970,  1.5279],
          [-1.1243,  1.6156, -2.1950, -0.9363,  1.7829, -1.4392],
          [-0.7423,  0.1364, -0.5768, -1.2655,  0.0349,  0.1311],
          [ 0.1253, -0.6836, -0.5449, -0.8237, -0.3981, -0.6251]]]])
tensor([[[[ 0.0224,  0.2490, -0.0379],
          [ 0.2551, -0.4870,  0.1686],
          [-0.2910, -0.8027, -0.2143]]]])
torch.Size([32, 3, 3, 3])
